- hosts: localhost
  become: yes

  tasks:
    - name: 'Install docker on Ubuntu/Debian Platform'
      apt: 
        name: docker-engine 
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
    - name: 'Install docker on Redhat/CentOS Platform'
      yum: 
        name: docker 
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: 'start docker service if not running'
      service:
        name: docker
        state: started
        enabled: yes

    - name: 'Install pip on Ubuntu/Debian Platform'
      apt: 
        name: python-pip 
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
    - name: 'Install pip on Redhat/CentOS Platform'
      yum: 
        name: python-pip 
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: 'Install docker-py'
      pip:
        name: docker-py
        state: present

    - name: 'Add iptable rule for port 4500'
      shell: iptables -I INPUT -p tcp --dport 4500 -j ACCEPT

    - name: Restart a container
      docker_container:
        name: AgileBot
        image: jsingh8/agilebot:firsttry
        state: started
        restart: yes
